import re

import httpx
import pytest

from stream_read_xbrl import (
    stream_read_xbrl_zip,
    stream_read_xbrl_daily_all,
)

expected_data = ({
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '1.0',
    'balance_sheet_date': '2022-08-31',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': 'None',
    'companies_house_registered_number': '14033910',
    'company_dormant': 'false',
    'company_id': '14033910',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': '7558.0',
    'date': '20220831',
    'debtors': 'None',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'Graham Chisnell Ltd',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': '-577.0',
    'net_current_assets_liabilities': '140.0',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2022-08-31',
    'period_start': '2022-08-31',
    'profit_loss_account_reserve': 'None',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': '-577.0',
    'staff_costs': 'None',
    'tangible_fixed_assets': '883.0',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': '1023.0',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '3.0',
    'balance_sheet_date': '2022-12-31',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': 'None',
    'companies_house_registered_number': '14068295',
    'company_dormant': 'true',
    'company_id': '14068295',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': '100.0',
    'date': '20221231',
    'debtors': 'None',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'Allied London Developments Four Limited',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': '100.0',
    'net_current_assets_liabilities': '100.0',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2022-12-31',
    'period_start': '2022-12-31',
    'profit_loss_account_reserve': 'None',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': '100.0',
    'staff_costs': 'None',
    'tangible_fixed_assets': 'None',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': '100.0',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '1.0',
    'balance_sheet_date': '2022-08-31',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': 'None',
    'companies_house_registered_number': 'NI681295',
    'company_dormant': 'false',
    'company_id': 'NI681295',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': '10346.0',
    'date': '20220831',
    'debtors': 'None',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'DAVIDSON ONLINE TRAINING (DOT) LIMITED',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': '3437.0',
    'net_current_assets_liabilities': '3887.0',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2022-08-31',
    'period_start': '2022-08-31',
    'profit_loss_account_reserve': 'None',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': '3437.0',
    'staff_costs': 'None',
    'tangible_fixed_assets': 'None',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': '3887.0',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '2.0',
    'balance_sheet_date': '2022-09-30',
    'called_up_share_capital': '2.0',
    'cash_bank_in_hand': '1624.0',
    'companies_house_registered_number': 'NI682066',
    'company_dormant': 'false',
    'company_id': 'NI682066',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': '21257.0',
    'date': '20220930',
    'debtors': '19633.0',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'Castlehill Pension Trustees Limited',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': '8382.0',
    'net_current_assets_liabilities': '6982.0',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2022-09-30',
    'period_start': '2022-09-30',
    'profit_loss_account_reserve': '8380.0',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': '2.0',
    'staff_costs': 'None',
    'tangible_fixed_assets': '1400.0',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': '8382.0',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '2.0',
    'balance_sheet_date': '2022-09-30',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': 'None',
    'companies_house_registered_number': 'NI682066',
    'company_dormant': 'false',
    'company_id': 'NI682066',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': 'None',
    'date': '20220930',
    'debtors': 'None',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'Castlehill Pension Trustees Limited',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': 'None',
    'net_current_assets_liabilities': 'None',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2021-09-01',
    'period_start': '2021-09-01',
    'profit_loss_account_reserve': 'None',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': 'None',
    'staff_costs': 'None',
    'tangible_fixed_assets': '1750.0',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': 'None',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '0.0',
    'balance_sheet_date': '2022-05-31',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': 'None',
    'companies_house_registered_number': 'OC437536',
    'company_dormant': 'true',
    'company_id': 'OC437536',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': 'None',
    'date': '20220531',
    'debtors': 'None',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'HARLING FARM LLP',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': 'None',
    'net_current_assets_liabilities': 'None',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': 'None',
    'period_start': 'None',
    'profit_loss_account_reserve': 'None',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': 'None',
    'staff_costs': 'None',
    'tangible_fixed_assets': 'None',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': 'None',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '2.0',
    'balance_sheet_date': '2022-07-31',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': '3057.0',
    'companies_house_registered_number': 'OC438238',
    'company_dormant': 'false',
    'company_id': 'OC438238',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': '3507.0',
    'date': '20220731',
    'debtors': '450.0',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'WESTERGAARD-WAKE LLP',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': '155318.0',
    'net_current_assets_liabilities': '3507.0',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2022-07-31',
    'period_start': '2022-07-31',
    'profit_loss_account_reserve': 'None',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': 'None',
    'staff_costs': 'None',
    'tangible_fixed_assets': '385000.0',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': '388507.0',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '2.0',
    'balance_sheet_date': '2022-07-31',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': 'None',
    'companies_house_registered_number': 'OC438238',
    'company_dormant': 'false',
    'company_id': 'OC438238',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': 'None',
    'date': '20220731',
    'debtors': 'None',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'WESTERGAARD-WAKE LLP',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': 'None',
    'net_current_assets_liabilities': 'None',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2021-07-06',
    'period_start': '2021-07-06',
    'profit_loss_account_reserve': 'None',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': 'None',
    'staff_costs': 'None',
    'tangible_fixed_assets': 'None',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': 'None',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '4.0',
    'balance_sheet_date': '2023-01-31',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': '6400.0',
    'companies_house_registered_number': 'SC720321',
    'company_dormant': 'false',
    'company_id': 'SC720321',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': '19321.0',
    'date': '20230131',
    'debtors': '12921.0',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'S&C Electrical and Plumbing Ltd',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': '-22737.0',
    'net_current_assets_liabilities': '-22780.0',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2023-01-31',
    'period_start': '2023-01-31',
    'profit_loss_account_reserve': '-22737.0',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': '-22737.0',
    'staff_costs': 'None',
    'tangible_fixed_assets': '24016.0',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': '1236.0',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '4.0',
    'balance_sheet_date': '2023-01-31',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': 'None',
    'companies_house_registered_number': 'SC720321',
    'company_dormant': 'false',
    'company_id': 'SC720321',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': 'None',
    'date': '20230131',
    'debtors': 'None',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'S&C Electrical and Plumbing Ltd',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': 'None',
    'net_current_assets_liabilities': 'None',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2022-01-18',
    'period_start': '2022-01-18',
    'profit_loss_account_reserve': 'None',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': 'None',
    'staff_costs': 'None',
    'tangible_fixed_assets': 'None',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': 'None',
    'turnover_gross_operating_revenue': 'None',
}, {
    'administrative_expenses': 'None',
    'average_number_employees_during_period': '0.0',
    'balance_sheet_date': '2023-02-28',
    'called_up_share_capital': 'None',
    'cash_bank_in_hand': 'None',
    'companies_house_registered_number': 'SC722766',
    'company_dormant': 'false',
    'company_id': 'SC722766',
    'cost_sales': 'None',
    'creditors_due_after_one_year': 'None',
    'creditors_due_within_one_year': 'None',
    'current_assets': '1.0',
    'date': '20230228',
    'debtors': 'None',
    'depreciation_other_amounts_written_off_tangible_intangible_fixed_assets': 'None',
    'entity_current_legal_name': 'G49SY LIMITED',
    'file_type': 'html',
    'gross_profit_loss': 'None',
    'net_assets_liabilities_including_pension_asset_liability': '1.0',
    'net_current_assets_liabilities': '1.0',
    'operating_profit_loss': 'None',
    'other_operating_charges_format2': 'None',
    'other_operating_income': 'None',
    'period_end': '2023-02-28',
    'period_start': '2023-02-28',
    'profit_loss_account_reserve': 'None',
    'profit_loss_for_period': 'None',
    'profit_loss_on_ordinary_activities_before_tax': 'None',
    'raw_materials_consumables': 'None',
    'run_code': 'Prod223_3384',
    'shareholder_funds': '1.0',
    'staff_costs': 'None',
    'tangible_fixed_assets': 'None',
    'tax_on_profit_or_loss_on_ordinary_activities': 'None',
    'taxonomy': '',
    'total_assets_less_current_liabilities': '1.0',
    'turnover_gross_operating_revenue': 'None',
})


@pytest.fixture
def mock_companies_house_daily_zip(httpx_mock):
    with open('fixtures/Accounts_Bulk_Data-2023-03-02.zip', 'rb') as f:
        httpx_mock.add_response(
            url='http://download.companieshouse.gov.uk/Accounts_Bulk_Data-2023-03-02.zip',
            content=f.read(),
        )

@pytest.fixture
def mock_companies_house_daily_html(httpx_mock):
    httpx_mock.add_response(
        url='http://download.companieshouse.gov.uk/en_accountsdata.html',
        content=b'<a href="Accounts_Bulk_Data-2023-03-02.zip">Link</a>',
    )


def test_stream_read_xbrl_zip(mock_companies_house_daily_zip):

    with httpx.stream('GET', 'http://download.companieshouse.gov.uk/Accounts_Bulk_Data-2023-03-02.zip') as r:
        columns, rows = stream_read_xbrl_zip(r.iter_bytes(chunk_size=65536))
        assert tuple((dict(zip(columns, row)) for row in rows)) == expected_data



def test_stream_read_xbrl_daily_all(mock_companies_house_daily_html, mock_companies_house_daily_zip):
    count = 0

    with stream_read_xbrl_daily_all() as (columns, rows):
        assert tuple((dict(zip(columns, row)) for row in rows)) == expected_data
